numero_1 = input("Dame Un Numero para el Dividendo")
numero_2 = input("Dame Otro Numero para el Divisor")
cociente = int(numero_1) / int(numero_2)
resto = int(numero_1) % int(numero_2)
print(f"Cocientes: {cociente}")
print(f"Restos: {resto}")